import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { validateRepresentativeSuite } from '../src/validators/scenarioValidator.js';
import { product, summarizeProduct } from '../src/core/product.js';
const suite = JSON.parse(fs.readFileSync('samples/representative-suite.json', 'utf8'));
const requiredDocs = ["README.md","AGENTS.md","SKILL.md","docs/requirements.md","docs/specification.md","docs/design.md","docs/implementation-plan.md","docs/test-plan.md","docs/manual-test.md","docs/installation-guide.md","docs/user-guide.md","docs/release-checklist.md","docs/responsibility-map.md","docs/ui-ux-polish.md","docs/post-mvp-roadmap.md","docs/competitive-benchmark.md","docs/evaluation-criteria.md","docs/qcds-evaluation.md","docs/qcds-remote-benchmark.md","docs/qcds-strict-gap-analysis.md","docs/qcds-strict-metrics.json","docs/qcds-regression-baseline.json","docs/security-privacy-checklist.md","docs/traceability-matrix.md","docs/strict-manual-test-addendum.md","docs/source-idea-pack.json","docs/release-evidence.json","docs/releases/v0.1.0-alpha.1.md"];
const allowedGrades = ["S+","S-","A+","A-","B+","B-","C+","C-","D+","D-"];
test('representative suite includes required scenario ids', () => assert.deepEqual(suite.scenarios.map((scenario) => scenario.id), ['happy-path','missing-required','warning','mixed-batch']));
test('expected results match evaluator output', () => { const validation = validateRepresentativeSuite(suite); assert.equal(validation.ok, true, JSON.stringify(validation, null, 2)); });
test('product summary exposes release and responsibility boundaries', () => { const summary = summarizeProduct(); assert.equal(summary.repo, product.repo); assert.ok(summary.requiredInputs.length >= 4); assert.ok(summary.responsibilities.length >= 4); assert.ok(summary.platformScope.length > 10); });
test('required closed alpha docs exist', () => assert.deepEqual(requiredDocs.filter((file) => !fs.existsSync(file)), []));
test('QCDS metrics use strict 10-grade scale when present', () => { if (!fs.existsSync('docs/qcds-strict-metrics.json')) return; const metrics = JSON.parse(fs.readFileSync('docs/qcds-strict-metrics.json', 'utf8')); for (const grade of Object.values(metrics.grades || {})) assert.ok(allowedGrades.includes(grade), 'invalid grade: ' + grade); });
